apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mtproxy.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
data:
  mtproxy.yml: |
    {{- toYaml (.Values.mtproxy.config | default .Values.config) | nindent 4 }}