apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vmstorage.fullname" . }}
  labels:
    {{- include "vmstorage.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vmstorage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vmstorage.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vmstorage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8400
            - containerPort: 8401
            - containerPort: 8482
              name: web 
          args: 
            - '-storageDataPath=/vmstorage-data'
          volumeMounts:
            - mountPath: /vmstorage-data
              name: vmstorage-pv
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: vmstorage-pv
          persistentVolumeClaim:
            claimName: vmstorage-pvc
