apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "etcd.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.client }}
      targetPort: {{ .Values.service.ports.client }}
      protocol: TCP
      name: http
  selector: 
    {{- include "etcd.selectorLabels" . | nindent 4 }}
