apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "etcd.selectorLabels" . | nindent 6 }}
  serviceName: {{ template "etcd.fullname" . }}-headless
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "etcd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }} 
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "etcd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- $etcdFullname := include "etcd.fullname" . }}
        {{- $etcdHeadlessServiceName := (printf "%s-%s" $etcdFullname "headless" | trunc 63 | trimSuffix "-") }}
        {{- $clusterDomain := .Values.clusterDomainSuffix }}
        {{- $etcdPeerProtocol := include "etcd.peerProtocol" . }}
        {{- $etcdPeerPort := int .Values.containerPorts.peer }}
        {{- $etcdClientProtocol := include "etcd.clientProtocol" . }}
        {{- $etcdClientPort := int .Values.containerPorts.client }}
        {{- $releaseNamespace := .Release.Namespace }}
        - name: {{ include "etcd.fullname" . }}
          {{- $image := coalesce .Values.etcd.image .Values.image }}
          image: "{{ default .Values.image.repository $image.repository }}:{{ default .Values.image.tag $image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy $image.pullPolicy }}
          securityContext:
            {{- toYaml (.Values.etcd.securityContext | default .Values.securityContext) | nindent 12 }}
          resources:
            {{- toYaml (.Values.etcd.resources | default .Values.resources) | nindent 12 }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_NAME
              value: "$(MY_POD_NAME)"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: {{ printf "%s://$(MY_POD_NAME).%s.%s.svc.%s:%d" $etcdClientProtocol $etcdHeadlessServiceName $releaseNamespace $clusterDomain $etcdClientPort | quote }}
            - name: ETCD_LISTEN_CLIENT_URLS
              value: {{ printf "%s://0.0.0.0:%d" $etcdClientProtocol $etcdClientPort | quote }}
            - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
              value: {{ printf "%s://$(MY_POD_NAME).%s.%s.svc.%s:%d" $etcdPeerProtocol $etcdHeadlessServiceName $releaseNamespace $clusterDomain $etcdPeerPort | quote }}
            - name: ETCD_LISTEN_PEER_URLS
              value: {{ printf "%s://0.0.0.0:%d" $etcdPeerProtocol $etcdPeerPort | quote }}
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ENABLE_V2
              value: "true"
            - name: ETCD_INITIAL_CLUSTER
              value: "{{ range $e, $i := until (int .Values.replicaCount) }}{{ if $i }},{{ end }}{{ printf "etcd-%d=%s://etcd-%d.%s.%s.svc.%s:%d" $i $etcdPeerProtocol $i $etcdHeadlessServiceName $releaseNamespace $clusterDomain $etcdPeerPort }}{{ end }}"
            - name: ETCD_INITIAL_CLUSTER_TOKEN
              value: "etcd-cluster-k8s"
            - name: ETCD_INITIAL_CLUSTER_STATE
              value: {{ default (ternary "new" "existing" .Release.IsInstall) .Values.initialClusterState | quote }}
            - name: ETCD_ON_K8S
              value: "yes"
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.client }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: data
              {{- with .Values.etcd.storage }}
              mountPath: {{ $.Values.etcd.storage.path }}
              {{- else }}
              mountPath: {{ $.Values.storage.path }}
              {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage.size }}
