apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmselect.fullname" . }}
  labels:
    {{- include "vmselect.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8481
      targetPort: 8481
      protocol: TCP
      name: http
  selector:
    {{- include "vmselect.selectorLabels" . | nindent 4 }}
