apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmagent.fullname" . }}
  labels:
    {{- include "vmagent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8429
      targetPort: 8429
      protocol: TCP
      name: http
  selector:
    {{- include "vmagent.selectorLabels" . | nindent 4 }}
