---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alerttrap-configuration
  namespace: default
data:

{{- if .Values.configs }}
{{ $root := . }}
  {{- range $key, $value := .Values.configs }}
  {{ $key }}: |
{{ tpl (toYaml $value | indent 4) $root }}
  {{- end -}}
{{- end -}}