---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grafana.fullname" . }}-cm
  #namespace: default
data:

{{- $datasources := coalesce .Values.grafana.datasources .Values.datasources }}
{{- $root := . }}
{{- range $key, $value := $datasources | default dict }}
  {{ $key }}: |
{{ tpl (toYaml $value | indent 4) $root }}
{{- end -}}

{{- $notifiers := coalesce .Values.grafana.notifiers .Values.notifiers }}
{{- range $key, $value := $notifiers | default dict }}
  {{ $key }}: |
{{ toYaml $value | indent 4 }}
{{- end -}}

{{- $dashboards := coalesce .Values.grafana.dashboards .Values.dashboards }}
{{- range $key, $value := $dashboards | default dict }}
  {{ $key }}: |
{{ toYaml $value | indent 4 }}
{{- end -}}

{{- range $path, $val := .Files.Glob  "dashboards/*" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print "grafana-" (regexReplaceAll "[._]+" (base $path) "-") "-cm" }}
  #namespace: default
data:
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}