---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "grafana.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.adminUser }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.adminPassword }}
            - name: GF_UNIFIED_ALERTING_ENABLED
              value: "false"
            - name: GF_ALERTING_ENABLED
              value: "true"
            #- name: GF_INSTALL_PLUGINS
            #  value: "camptocamp-prometheus-alertmanager-datasource"
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            {{- if .Values.datasources }}
            {{- range $key, $value := .Values.datasources }}
            - mountPath: /etc/grafana/provisioning/datasources/{{ $key }}
              name: grafana-volume
              subPath: {{ $key }}
            {{- end -}}
            {{- end }}
            {{- if .Values.notifiers }}
            {{- range $key, $value := .Values.notifiers }}
            - mountPath: /etc/grafana/provisioning/notifiers/{{ $key }}
              name: grafana-volume
              subPath: {{ $key }}
            {{- end -}}
            {{- end }}
            {{- if .Values.dashboards }}
            {{- range $key, $value := .Values.dashboards }}
            - mountPath: /etc/grafana/provisioning/dashboards/{{ $key }}
              name: grafana-volume
              subPath: {{ $key }}
            {{- end -}}
            {{- end }}
            {{- range $path, $_ :=  .Files.Glob  "dashboards/*" }}
            - mountPath: /var/lib/grafana/dashboards/{{ base $path }}
              name: {{ print "grafana-" (regexReplaceAll "[._]+" (base $path) "-") }}
              subPath: {{ base $path }}
            {{- end }}
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: {{ template "grafana.fullname" . }}-pvc
        - name: grafana-volume
          configMap:
            name: {{ template "grafana.fullname" . }}-cm
        {{- range $path, $_ :=  .Files.Glob  "dashboards/*" }}
        - name: {{ print "grafana-" (regexReplaceAll "[._]+" (base $path) "-") }}
          configMap:
            name: {{ print "grafana-" (regexReplaceAll "[._]+" (base $path) "-") "-cm" }}
        {{- end }}

