apiVersion: v1
kind: Service
metadata:
  name: renderer
  labels:
    {{- include "grafana-image-renderer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "grafana-image-renderer.selectorLabels" . | nindent 4 }}
