apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2379
      targetPort: 2379
      protocol: TCP
      name: http
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
