{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "vmselect.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vmselect.labels" . | nindent 4 }}
spec:
{{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "vmselect.fullname" . }}
      {{- include "vmselect.selectorLabels" . | nindent 6 }}
{{- end }}