---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grafana.fullname" . }}-cm
  namespace: default
data:

{{- if .Values.datasources }}
{{ $root := . }}
  {{- range $key, $value := .Values.datasources }}
  {{ $key }}: |
{{ tpl (toYaml $value | indent 4) $root }}
  {{- end -}}
{{- end -}}

{{- if .Values.notifiers }}
  {{- range $key, $value := .Values.notifiers }}
  {{ $key }}: |
{{ toYaml $value | indent 4 }}
  {{- end -}}
{{- end -}}

{{- if .Values.dashboards }}
  {{- range $key, $value := .Values.dashboards }}
  {{ $key }}: |
{{ toYaml $value | indent 4 }}
  {{- end -}}
{{- end -}}

{{- range $path, $val := .Files.Glob  "dashboards/*" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print "grafana-" (regexReplaceAll "[._]+" (base $path) "-") "-cm" }}
  namespace: default
data:
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}