apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netserver.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
data:
  netserver.yml: |
    {{- toYaml (.Values.netserver.config | default .Values.config) | nindent 4 }}