---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netserver-configuration
  namespace: default
data:
  netserver.yaml: |-
    global:
      cert_file:      ""
      cert_key:       ""

    db:
      client:         "sqlite3"
      conn_string:    "/tmp/netmap.db"
      limit:          1000000
      flush_interval: "24h"

    notifier:
      urls:           ["http://localhost:9093"]