---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netserver-cm
data:
  netserver.yaml: |-
    global:
      cert_file:      ""
      cert_key:       ""

    db:
      client:         "couchdb"
      conn_string:    "http://couchdb:5984"
      limit:          1000000
      username:       "admin"
      password:       "password"

    notifier:
      urls:           ["http://alertmanager:9093"]