apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netserver.fullname" . }}
  labels:
    {{- include "netserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "netserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "netserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "netserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- $image := coalesce .Values.netserver.image .Values.image }}
          image: "{{ $image.repository }}:{{ $image.tag }}"
          imagePullPolicy: {{ $image.pullPolicy }}
          securityContext:
            {{- toYaml (.Values.netserver.securityContext | default .Values.securityContext) | nindent 12 }}
          resources:
            {{- toYaml (.Values.netserver.resources | default .Values.resources) | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: web
          args:
            - '-web.listen-address=:{{ .Values.service.port }}'
            - '-config.file=/netserver-conf/netserver.yml'
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - mountPath: /netserver-conf
              name: netserver-volume
            - name: storage
              mountPath: /storage
      volumes:
        - name: netserver-volume
          configMap:
            name: netserver-cm
        - name: storage
          emptyDir: {}
