{{- if and (.Values.fail) (not .Values.netserver.image) }}
{{- fail "Installation is not allowed in this cluster" }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "netserver.fullname" . }}
  labels:
    {{- include "netserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.peerPort }}
      targetPort: {{ .Values.service.peerPort }}
      protocol: TCP
      name: peer
  selector: 
    {{- include "netserver.selectorLabels" . | nindent 4 }}