---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
      protocol: TCP
    - name: web
      port: 9216
      targetPort: 9216
      protocol: TCP
    - name: mongo-express
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: mongo
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9216'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.32.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9216
              name: web
          args:
            - '--mongodb.uri=mongodb://root:example@127.0.0.1:27017/'
            - '--discovering-mode'
            - '--collector.dbstats'
            - '--collector.topmetrics'
        - name: mongo-express
          image: mongo-express:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: example
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://root:example@localhost:27017/