apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cdserver.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
data:
  cdserver.yml: |
    {{- toYaml (.Values.cdserver.config | default .Values.config) | nindent 4 }}