apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cdserver.fullname" . }}
  labels:
    {{- include "cdserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cdserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "cdserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "cdserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- $image := coalesce .Values.cdserver.image .Values.image }}
          image: "{{ default .Values.image.repository $image.repository }}:{{ default .Values.image.tag $image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy $image.pullPolicy }}
          securityContext:
            {{- toYaml (.Values.cdserver.securityContext | default .Values.securityContext) | nindent 12 }}
          resources:
            {{- toYaml (.Values.cdserver.resources | default .Values.resources) | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          args:
            - '-web.listen-address=:{{ .Values.service.port }}'
            - '-config.file=/cdserver-conf/cdserver.yml'
          env:
            {{- $releaseNamespace := .Release.Namespace }}
            {{- range .Values.secrets.list }}
            {{- if (lookup "v1" "Secret" $releaseNamespace .) }}
            - name: '{{ . | replace "." "_" | upper }}_USERNAME'
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: username
            - name: '{{ . | replace "." "_" | upper }}_PASSWORD'
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: password
            {{- end }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /cdserver-conf
            {{- range $path, $_ :=  .Files.Glob  "configs/*" }}
            - mountPath: /config/{{ base $path }}
              name: {{ print "cdserver-" (regexReplaceAll "[._]+" (base $path) "-") }}
              subPath: {{ base $path }}
            {{- end }}
            {{- range .Values.secrets.certs }}
            - name: '{{ . | replace "." "-" }}'
              mountPath: /etc/ssl/certs/{{ . }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cdserver.fullname" . }}-cm
        {{- range $path, $_ :=  .Files.Glob  "configs/*" }}
        - name: {{ print "cdserver-" (regexReplaceAll "[._]+" (base $path) "-") }}
          configMap:
            name: {{ print "cdserver-" (regexReplaceAll "[._]+" (base $path) "-") "-cm" }}
        {{- end }}
        {{- range .Values.secrets.certs }}
        - name: '{{ . | replace "." "-" }}'
          secret:
            secretName: {{ . }}
        {{- end }}
