---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alerttrap.fullname" . }}-cm
  labels:
    {{- include "alerttrap.labels" . | nindent 4 }}
data:
  alerttrap.yaml: |-
    {{- toYaml (mergeOverwrite .Values.config (.Values.alerttrap.config | default dict)) | nindent 4 }}

{{- range $path, $val := .Files.Glob  "custom/*" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ print "alerttrap-" (regexReplaceAll "[._]+" (base $path) "-") "-cm" }}
data:
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}