---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alerttrap.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  alerttrap.yaml: |-
    {{- toYaml .Values.config | nindent 6 }}