---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alerttrap.fullname" . }}-cm
  labels:
    {{- include "alerttrap.labels" . | nindent 4 }}
data:
  alerttrap.yaml: |-
    {{- toYaml (mergeOverwrite .Values.config (.Values.alerttrap.config | default dict)) | nindent 4 }}