---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alerttrap.fullname" . }}-cm
  labels:
    {{- include "alerttrap.labels" . | nindent 4 }}
data:
  alerttrap.yaml: |-
    {{- toYaml (.Values.alerttrap.config | default .Values.config) | nindent 4 }}