{{- if gt (len .Values.alerttrap.config) 0 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alerttrap.fullname" . }}-cm
  labels:
    {{- include "alerttrap.labels" . | nindent 4 }}
data:
  alerttrap.yaml: |-
    {{- toYaml .Values.alerttrap.config | nindent 4 }}
{{- end }}