apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alerttrap.fullname" . }}
  labels:
    {{- include "alerttrap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "alerttrap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "alerttrap.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ $.Values.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ include "alerttrap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- $image := coalesce .Values.alerttrap.image .Values.image }}
          image: "{{ default .Values.image.repository $image.repository }}:{{ default .Values.image.tag $image.tag }}"
          imagePullPolicy: {{ default .Values.image.pullPolicy $image.pullPolicy }}
          securityContext:
            {{- toYaml (.Values.alerttrap.securityContext | default .Values.securityContext) | nindent 12 }}
          resources:
            {{- toYaml (.Values.alerttrap.resources | default .Values.resources) | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: web
          args:
            - '-web.listen-address=:{{ .Values.service.port }}'
            - '-web.dir=/data/web'
            - '-config.file=/alerttrap-conf/alerttrap.yaml'
          resources:
            {{- if and .Values.alerttrap .Values.alerttrap.resources }}
            {{- toYaml .Values.alerttrap.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.resources | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /alerttrap-conf
            - name: storage
              mountPath: /storage
      volumes:
        - name: config
          configMap:
            name: {{ include "alerttrap.fullname" . }}-cm
        - name: storage
          emptyDir: {}
