---
apiVersion: v1
kind: Secret
metadata:
  name: alerttrap-credentials
type: Opaque
data:
  alerttrapBasicAuth: {{ (printf "%s:%s" .Values.config.global.security.admin_user .Values.config.global.security.admin_password) | b64enc | quote }}