apiVersion: v1
kind: Service
metadata:
  name: {{ include "vminsert.fullname" . }}
  labels:
    {{- include "vminsert.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8480
      targetPort: 8480
      protocol: TCP
      name: http
  selector:
    {{- include "vminsert.selectorLabels" . | nindent 4 }}
