apiVersion: v1
kind: Service
metadata:
  name: {{ include "vmstorage.fullname" . }}
  labels:
    app: {{ template "vmstorage.name" . }}
    {{- include "vmstorage.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.vmselectPort }}
      targetPort: vmselect
      protocol: TCP
      name: vmselect
    - port: {{ .Values.service.vminsertPort }}
      targetPort: vminsert
      protocol: TCP
      name: vminsert
  selector:
    app: {{ include "vmstorage.fullname" . }}
    {{- include "vmstorage.selectorLabels" . | nindent 4 }}
