groups:

- name: telegraf
  rules:
  
  - alert: sysmonSysCpuPct
    expr: round(cpu_usage_active{cpu="cpu-total"}) >= 90
    labels:
      severity: critical
    annotations:
      summary: "CPU average utilization value. Host={{ $labels.host }} Value={{ $value }}%"

  - alert: sysmonSysMemPct
    expr: round(mem_used_percent) > 90
    labels:
      severity: critical
    annotations:
      summary: "Memory average utilization value. Host={{ $labels.host }} Value={{ $value }}%"
      
  - alert: sysmonSysSwapPct
    expr: round(swap_used_percent) > 90
    labels:
      severity: warning
    annotations:
      summary: "Swap average utilization value. Host={{ $labels.host }} Value={{ $value }}%"
      
  - alert: sysmonDiskUsedPct
    expr: round(disk_used_percent{}) >= 95
    labels:
      severity: critical
    annotations:
      summary: "Disk usage percentage. Host={{ $labels.host }} Value={{ $value }}%"

  - alert: sysmonProcState
    expr: procstat_lookup_running == 0
    labels:
      severity: critical
    annotations:
      summary: "Application status. Name={{ $labels.application }} Appl_id={{ $labels.appl_id }} Instance={{ $labels.instance }} Stand={{ $labels.stand }}"
      
  - alert: directoryExists
    expr: filestat_exists == 0
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Missing application directory on server. File={{ $labels.file }}"
      
  - alert: confdGenerateTemplate
    expr: confd_success > 2
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Telegraf generating templates. Host={{ $labels.host }} Template={{ $labels.src }}"
      
  - alert: httpResultCode
    expr: http_response_result_code > 0
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Incorrect response result from http plugin. Result={{ $labels.result }} Server={{ $labels.server }}"