{{- if eq .Values.server.configMap "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vmalert.configname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "vmalert.labels" . | nindent 4 }}
data:
  alert-rules.yaml: |
    {{ toYaml .Values.server.config.alerts | nindent 4 }}
{{- range $path, $_ :=  .Files.Glob  "alertrules/*" }}
  {{ base $path }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}

